version: '3.1'

services:
  wordpress:
    env_file:
      - /home/ubuntu/wordpress.env
    image: wordpress
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/www/html:/var/www/html
