global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: "10s"

scrape_configs:
  - job_name: 'prometheus'
    ec2_sd_configs:
      - region: us-east-2
        port: 9100
    relabel_configs:
        # Only monitor instances with a Name starting with "SD Demo"
      - source_labels: [__meta_ec2_tag_Name]
        regex: wordpress-asg
        action: keep
        # Use the instance ID as the instance label
      # - source_labels: [__meta_ec2_instance_id]
      #   target_label: instance